# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  job1: #<- job ID
    runs-on: ubuntu-latest
    outputs: #declaring output(s) for specific job
      output: ${{ steps.step1.outputs.test }}
    steps:
      - name: step 1 
        id: step1 
        # {name}={value} >> "$GITHUB_OUTPUT"
        run: |
          echo "test=hello" >> "$GITHUB_OUTPUT" 


  job2:
    runs-on: ubuntu-latest
    needs: job1
    env:
      RESULT: ${{needs.job1.result}}
      OUTPUT: ${{needs.job1.outputs.output}}
    steps:
      - name: Use output value from job1
        id: step3 # <- step ID
        #Possible values are success, failure, cancelled, or skipped. Also GitHub automatically evaluates the if conditional as an expression .
        if: env.RESULT=='success' 
        run: |
          echo "$OUTPUT $RESULT"
          echo "message=Input for the next step" >> $GITHUB_OUTPUT
      - name: Use value from the previous step
        env:
          OUTPUT2: ${{steps.step3.outputs.message}}
        run: echo "$OUTPUT2"

  example_matrix:
    runs-on: ubuntu-latest
    outputs:
      output: ${{steps.step5.outputs.matrix}}
    strategy:
      matrix:
        who-to-greet: [Ivo, Pero, Miško]
    steps:
      - uses: actions/hello-world-javascript-action@main
        id: step4
        with:
          who-to-greet: ${{ matrix.who-to-greet}}
      - name: Output matrix
        id: step5
        run: echo "matrix=${{ (matrix.who-to-greet)}}" >> $GITHUB_OUTPUT
        

  test_new_env:
    needs: example_matrix
    runs-on: ubuntu-latest
    environment: dev-env
    env:
      NAMES: ${{ (needs.example_matrix.outputs.output)}}
    steps:
      - name: echo env variable name and context values
        env: 
          ENV_VAR: ${{ (vars.DUMMY_VALUE) }}
        run: | 
          echo "$ENV_VAR"
          echo "$NAMES"
      

  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          
  call_reusable_workflow:
    uses: ./.github/workflows/reusable_workflow.yml
    with: 
      name: Hello
    secrets:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      token: ${{ secrets.DOCKERHUB_TOKEN }}

  print_out_job_context:
    runs-on: ubuntu-latest
    steps:
      - name: Print out job context
        run: echo "${{ toJSON(job)}}"


  generate_labels:
    name: Generate  labels
    runs-on: ubuntu-latest
    outputs:
      labels: ${{ steps.set-up-labels.outputs.labels_for_the_next_job }}
    steps:
        - name: Set up label list
          id: set-up-labels
          run: |
            echo "labels_for_the_next_job=self-hosted, Windows, X64" >> $GITHUB_OUTPUT


  consume_labels:
    name: Use labels from previous job
    runs-on: [self-hosted, test]
    needs: generate_labels
    steps:
      - name: Print out labels as a list
        run: |
          echo "${{fromJSON(toJSON(needs.generate_labels.outputs)).labels}}"
          echo "${{needs.generate_labels.outputs.labels}}"

    
 
