on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
    secrets:
      username:
        required: true
      token:
        required: true
  
jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Welcome message
        run: |
          echo Welcome to reusable workflow!
          echo ${{ inputs.name }}
          echo ${{ secrets.token}}
        
