on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      labels:
        required: true
        type: string

  
jobs:
  extracted-labels:
    runs-on: windows-latest
    env:
      JSON_DOC: ${{toJson(inputs)}}
    outputs:
      json: ${{env.JSON_DOC}}
      labels: ${{ steps.labels_json.outputs.labels }}
    steps:
      - name: Welcome message
        id: JSON
        run: |
          printf '%s\n' "$JSON_DOC" > foo.json
          cat foo.json

      - name: extract labels
        id: extractLabels
        run: |
          echo "$JSON_DOC"
          echo "${{fromJson(env.JSON_DOC)}}"

      - name: convert to JSON
        id: labels_json 
        run: |
          $labels_string = "${{ inputs.labels }}"
          $labels_array = @($labels_string -split ',\s*')
          $labels_json = ConvertTo-Json $labels_array -Compress -Depth 100 | Out-String
          echo "labels=$labels_json" >> $ENV:GITHUB_OUTPUT
        shell: powershell

      - name: test output
        run: echo "${{ (steps.labels_json.outputs.labels)}}"

  run-on-extracted-labels:
    needs: extracted-labels
    runs-on: ${{ inputs.labels }}
    steps:
      - name: finally
        run: |
          echo "success"
          echo "${{ fromJson(needs.extracted-labels.outputs.labels) }}"


        
