on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      labels:
        required: true
        type: string

  
jobs:
  extracted-labels:
    runs-on: ubuntu-latest
    outputs:
      JSON_DOC: ${{toJson(inputs)}}
    steps:
      - name: Welcome message
        id: JSON
        run: |
          printf '%s\n' "$JSON_DOC" > foo.json
          cat foo.json

      - name: extract labels
        id: extractLabels
        run: |
          echo "labels=${{(inputs.labels)}}" >> $GITHUB_OUTPUT
          echo "$JSON_DOC" 
          echo "${{fromJson(steps.JSON.outputs).labels}}" 
          echo "$GITHUB_OUTPUT"

  run-on-extracted-labels:
    needs: extracted-labels
    runs-on: ${{fromJson(needs.extracted-labels.outputs.JSON_DOC).labels}}

        
