on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      labels:
        required: true
        type: string

  
jobs:
  extracted-labels:
    runs-on: ubuntu-latest
    env:
      JSON_DOC: ${{toJson(inputs)}}
    outputs:
      json: ${{steps.JSON.outputs.JSON_DOC}}
    steps:
      - name: Welcome message
        id: JSON
        run: |
          printf '%s\n' "$JSON_DOC" > foo.json
          cat foo.json

      - name: extract labels
        id: extractLabels
        run: |
          echo "$JSON_DOC" 

  run-on-extracted-labels:
    needs: extracted-labels
    runs-on: ubuntu-latest
    steps:
      - name: finally
        run: |
          echo "${{needs.extracted-labels.outputs.json.labels}}"

        
