on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      labels:
        required: true
        type: string

  
jobs:
  run-on-extracted-labels:
    runs-on: ${{fromJson(toJson(inputs.labels))}}
    outputs:
      array:  ${{ steps.extractLabels.outputs.labels }}
    steps:
      - name: Welcome message
        run: |
          echo Welcome to reusable workflow!
          echo ${{ inputs.name }}

      - name: extract labels
        id: extractLabels
        run: |
          echo "labels=${{(inputs.labels)}}" >> $GITHUB_OUTPUT
          echo "${{toJson(inputs.labels)}}" 
          echo "${{toJson(inputs)}}" 
          echo "${{fromJson(toJson(inputs.labels))}}" 
          echo "$GITHUB_OUTPUT"

  

        
