on:
  workflow_call:
    inputs:
      label:
        required: true
        type: string

  
jobs:
  extracted-labels:
    runs-on: windows-latest
    env:
      JSON_DOC: ${{ inputs.label}}
    outputs:
      json: ${{env.JSON_DOC}}
      labels: ${{ steps.labels_json.outputs.labels }}
    steps:
      - name: Welcome message
        id: JSON
        run: |
          printf '%s\n' "$JSON_DOC" > foo.json
          cat foo.json

      - name: convert to JSON
        id: labels_json 
        run: |
          $labels_string = "${{ inputs.label}}"
          $labels_array = @($labels_string -split ',\s*' | ForEach-Object { "$_" })
          $labels_json = ConvertTo-Json $labels_array -Compress -Depth 100 | Out-String
          Write-Output "::set-output name=labels::$labels_json"
        shell: powershell
      

      - name: test output
        run: echo "${{ fromJson(steps.labels_json.outputs.labels)}}"

  run-on-extracted-labels:
    needs: extracted-labels
    runs-on: "${{ needs.extracted-labels.outputs.labels}}"
    steps:
      - name: finally
        run: |
          echo "success"
          echo "${{ fromJson(needs.extracted-labels.outputs.labels) }}"
   
