on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      labels:
        required: true
        type: string

  
jobs:
  run-on-extracted-labels:
    runs-on: ubuntu-latest
    outputs:
      array:  ${{ steps.extractLabels.outputs.labels }}
    env:
      JSON_DOC: ${{toJson(inputs.labels)}}
    steps:
      - name: Welcome message
        run: |
          printf '%s\n' "$JSON_DOC" > foo.json
          cat foo.json

      - name: extract labels
        id: extractLabels
        run: |
          echo "labels=${{(inputs.labels)}}" >> $GITHUB_OUTPUT
          echo "${{toJson(inputs.labels)}}" 
          echo "${{toJson(inputs)}}" 
          echo "${{fromJson(toJson(inputs.labels))}}" 
          echo "$GITHUB_OUTPUT"

  

        
