on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      labels:
        required: true
        type: string

  
jobs:
  welcome:
    runs-on: ubuntu-latest
    outputs:
      array:  ${{ steps.extractLabels.outputs.labels }}
    steps:
      - name: Welcome message
        run: |
          echo Welcome to reusable workflow!
          echo ${{ inputs.name }}

      - name: extract labels
        id: extractLabels
        run: |
          echo "labels=${{toJson(inputs.labels)}}" >> $GITHUB_OUTPUT
          echo "${{toJson(inputs.labels)}}" 
  
  run-on-extracted-labels:
    needs: welcome
    runs-on: ubuntu-latest
    steps:
      - name: Print labels
        run: |
          echo ${{(needs.welcome.outputs.array)}}
        
